path: D:/Desktop/Adas_test/ds_segmentation/ # dataset root dir
train: images # train images (relative to 'path')
val: images # val images (relative to 'path')
test: # test images (optional)

names:
    0: road
    1: not_road
